name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify the desired Node.js version here

      - name: Install Dependencies
        run: npm install # Use npm to install dependencies

      - name: Build Project
        run: npm run build # Run the build script defined in your package.json

      - name: List Build Directory
        run: ls -R dist # List all files and directories in the 'dist' directory

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: "github-pages"
